# Generated by Django 2.1.5 on 2020-02-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
